### ISSUE TITLE
network and docker-compose

### ISSUE THREAD

**Issue by gperreymond** [ccali14/docker-network#1]
Hi, if you use networks in docker-compose to start your env, then your command :

`sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}'`

Will return nothing, try to use something like :

`sudo docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'`

**Comment by cagataycali** [comment]
Could you please PR for these.

Thx your contribution.

**Comment by cagataycali** [comment]
Issue resolved, I did {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} in format. thx @gperreymond
